#!/usr/bin/env python3
import File
import Shell
import Debug
import System

if File.exists("~/.ssh/id_ed25519.pub"):
    if System.is_linux:
        Shell.run_string("xclip -sel clip < ~/.ssh/id_ed25519.pub")
    else:
        Debug.throw("Invalid platform")
else:
    Debug.throw("No ssh key")